services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: unless-stopped

  guacweb:
    container_name: guacweb
    image: guacamole/guacamole
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_HOSTNAME: guacamole-sql
      MYSQL_PASSWORD: pass
      MYSQL_USER: guacamole_user
      GUACD_HOSTNAME: guacd
    depends_on:
      - guacamole-sql
      - guacd
            
  guacamole-sql:
    container_name: guacamole-sql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./dbdata:/var/lib/mysql

  db-setup:
    container_name: db-setup
    build:
      context: ./sql_scripts
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - guacamole-sql
    environment:
      MYSQL_HOST: guacamole-sql
      MYSQL_ROOT_PASSWORD: pass
